#!/usr/bin/env bash
set -e

# Colors
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

DNSMASQ_CONF_DIR="/etc/dnsmasq.d"
MACULA_CONF="${DNSMASQ_CONF_DIR}/macula.conf"

echo ""
echo "╔════════════════════════════════════════════════════════╗"
echo "║  Macula Infrastructure - Dnsmasq Setup                 ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}✗${NC} This script must be run as root (use sudo)"
    exit 1
fi

# Detect OS
if [ -f /etc/os-release ]; then
    . /etc/os-release
    OS=$ID
else
    echo -e "${RED}✗${NC} Cannot detect OS"
    exit 1
fi

# Install dnsmasq
echo -e "${CYAN}▸${NC} Installing dnsmasq..."

case $OS in
    ubuntu|debian)
        apt-get update -qq
        apt-get install -y dnsmasq socat
        ;;
    arch|manjaro)
        pacman -S --noconfirm dnsmasq socat
        ;;
    *)
        echo -e "${RED}✗${NC} Unsupported OS: $OS"
        echo "Please install dnsmasq and socat manually"
        exit 1
        ;;
esac

echo -e "${GREEN}✓${NC} Dnsmasq and socat installed"
echo ""

# Stop dnsmasq if running
systemctl stop dnsmasq 2>/dev/null || true

# Create dnsmasq.d directory
mkdir -p "$DNSMASQ_CONF_DIR"

# Create macula configuration
echo -e "${CYAN}▸${NC} Creating dnsmasq configuration..."

cat > "$MACULA_CONF" <<'EOF'
# Macula Infrastructure DNS Configuration
# Generated by setup-dnsmasq.sh

# Listen on localhost only (security)
listen-address=127.0.0.1
bind-interfaces

# Don't read /etc/hosts
no-hosts

# Infrastructure services (127.0.0.1) - Host Docker Compose
address=/home.macula.local/127.0.0.1
address=/registry.macula.local/127.0.0.1
address=/dns.macula.local/127.0.0.1
address=/dns-admin.macula.local/127.0.0.1

# Application services (127.0.0.2) - KinD Cluster
address=/console.macula.local/127.0.0.2
address=/bootstrap.macula.local/127.0.0.2
address=/peer1.macula.local/127.0.0.2
address=/peer2.macula.local/127.0.0.2

# Observability stack (127.0.0.3-6)
address=/prometheus.macula.local/127.0.0.3
address=/grafana.macula.local/127.0.0.4
address=/loki.macula.local/127.0.0.5
address=/tempo.macula.local/127.0.0.6

# Development tools (127.0.0.7)
address=/draw.macula.local/127.0.0.7

# Data services (127.0.0.8-9)
address=/postgres.macula.local/127.0.0.8
address=/s3.macula.local/127.0.0.9
address=/s3-console.macula.local/127.0.0.9

# Cache settings
cache-size=1000
EOF

echo -e "${GREEN}✓${NC} Configuration created at $MACULA_CONF"
echo ""

# Configure NetworkManager to use dnsmasq (if present)
if command -v nmcli &> /dev/null; then
    echo -e "${CYAN}▸${NC} Configuring NetworkManager to use dnsmasq..."

    # Create NetworkManager dnsmasq configuration
    mkdir -p /etc/NetworkManager/conf.d
    cat > /etc/NetworkManager/conf.d/dnsmasq.conf <<EOF
[main]
dns=dnsmasq
EOF

    # Create NetworkManager dnsmasq.d directory
    mkdir -p /etc/NetworkManager/dnsmasq.d

    # Symlink our config
    ln -sf "$MACULA_CONF" /etc/NetworkManager/dnsmasq.d/macula.conf

    # Restart NetworkManager
    systemctl restart NetworkManager

    echo -e "${GREEN}✓${NC} NetworkManager configured"
else
    echo -e "${YELLOW}⚠${NC}  NetworkManager not found, starting dnsmasq directly"

    # Enable and start dnsmasq
    systemctl enable dnsmasq
    systemctl start dnsmasq

    echo -e "${GREEN}✓${NC} Dnsmasq started"
    echo ""
    echo -e "${YELLOW}⚠${NC}  You may need to configure your system to use 127.0.0.1 as nameserver"
    echo "     Edit /etc/resolv.conf to add: nameserver 127.0.0.1"
fi

echo ""

# Test DNS resolution
echo -e "${CYAN}▸${NC} Testing DNS resolution..."
sleep 2  # Give dnsmasq a moment to start

TEST_HOSTS=(
    "registry.macula.local 127.0.0.1"
    "console.macula.local 127.0.0.2"
    "grafana.macula.local 127.0.0.4"
    "postgres.macula.local 127.0.0.7"
)

ALL_OK=true
for test in "${TEST_HOSTS[@]}"; do
    host=$(echo $test | cut -d' ' -f1)
    expected_ip=$(echo $test | cut -d' ' -f2)

    resolved_ip=$(dig +short @127.0.0.1 "$host" 2>/dev/null | head -n1)

    if [ "$resolved_ip" = "$expected_ip" ]; then
        echo -e "  ${GREEN}✓${NC} $host → $resolved_ip"
    else
        echo -e "  ${RED}✗${NC} $host → $resolved_ip (expected $expected_ip)"
        ALL_OK=false
    fi
done

echo ""

if [ "$ALL_OK" = true ]; then
    echo "╔════════════════════════════════════════════════════════╗"
    echo "║  Dnsmasq Setup Complete                                ║"
    echo "╚════════════════════════════════════════════════════════╝"
    echo ""
    echo -e "${GREEN}All DNS entries configured successfully!${NC}"
    echo ""
    echo "Services will be accessible at:"
    echo "  📦 http://registry.macula.local"
    echo "  🌐 http://dns-admin.macula.local"
    echo "  🎮 http://console.macula.local"
    echo "  📊 http://grafana.macula.local"
    echo ""
else
    echo -e "${YELLOW}⚠${NC}  Some DNS entries did not resolve correctly"
    echo "Check dnsmasq logs: journalctl -u dnsmasq -n 50"
fi
